version: '3.8'

services:
#   server:
#     build: ./server
#     image: lust_server:latest
#     container_name: server
#     restart: always
#     ports:
#       - "8080:8080"
  db:
    build: ./database
    image: lust_db:latest
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_volume:/data/db/

volumes:
  db_volume: